name: Publish DisTube
on:
  release:
    types: [created]
jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Login
        run: npm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Publish
        run: npm run publish:stable
